apiVersion: chainloop.dev/v1
kind: Contract
metadata:
  name: retail-banking-app-release-gate
spec:
  policies:
    attestation:
      - ref: source-commit
        with:
          check_signature: "true"
          check_author_verified: "true"

      - ref: check-compliance-requirement
        with:
          framework_name: chainloop-best-practices
          requirement_name: sast-analysis,code-coverage,mutation-score
        gate: true

  runner:
    type: GITHUB_ACTION
